-- PGADMIN
-- User: admin
-- Password: admin
-- Version: PostgreSQL 17

-- ########################################################################################################################################
-- CREATE TABLES
-- ########################################################################################################################################

CREATE TABLE PERFILES(
	CODIGO VARCHAR(50),
	DESCRIPCION VARCHAR(200),
	PRIMARY KEY (CODIGO)
);


CREATE TABLE USUARIOS(
	USUARIO VARCHAR(50),
	NOMBRE VARCHAR(200),
	CLAVE TEXT NOT NULL,
	SALT TEXT NOT NULL,
	ACTIVO INTEGER DEFAULT 1,
	PERFIL VARCHAR(200),
	EMAIL VARCHAR(200),
	VERIFICADO INTEGER,
	PRIMARY KEY (USUARIO)	
)


ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_PERFILES_FK FOREIGN KEY (PERFIL) REFERENCES PERFILES(CODIGO);
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_UNIQUE UNIQUE (EMAIL);


CREATE TABLE DIALOGOS(
	CODIGO VARCHAR(50),
	DESCRIPCION VARCHAR(200),
	PRIMARY KEY (CODIGO)
);

CREATE TABLE PERMISOS(
	PERFIL VARCHAR(50),
	DIALOGO VARCHAR(50),
	ALTA INTEGER DEFAULT 0,
	BAJA INTEGER DEFAULT 0,
	CONSULTA INTEGER DEFAULT 0,
	MODIF INTEGER DEFAULT 0,
	PRIMARY KEY (PERFIL , DIALOGO)
);

ALTER TABLE PERMISOS ADD CONSTRAINT PERMISOS_PERFILES_FK FOREIGN KEY (PERFIL) REFERENCES PERFILES(CODIGO);
ALTER TABLE PERMISOS ADD CONSTRAINT PERMISOS_DIALOGOS_FK FOREIGN KEY (DIALOGO) REFERENCES DIALOGOS(CODIGO);

CREATE TABLE LOG_PROCESOS(
	ID SERIAL PRIMARY KEY,
    UBICACION VARCHAR(200),
    STACKTRACE TEXT,
    ERROR_MESSAGE TEXT,
    FECHA TIMESTAMP
);

CREATE TABLE MASCOTAS(
	ID SERIAL PRIMARY KEY,
	USUARIO VARCHAR(50),
	NOMBRE VARCHAR(50),
	EDAD INTEGER,
	PESO INTEGER,
	SEXO VARCHAR(50),
	ACTIVO INTEGER,
	IMAGEURL VARCHAR(500)
);

ALTER TABLE MASCOTAS ADD CONSTRAINT MASCOTAS_USUARIOS_FK FOREIGN KEY (USUARIO) REFERENCES USUARIOS(USUARIO);

INSERT INTO MASCOTAS (ID, USUARIO, NOMBRE, EDAD, PESO, SEXO, IMAGEURL, ACTIVO) values (1, 'Diego', 'Juanita', 25, 5, 'Masculino', '/Imagenes/Perro1.jpg', 1);
INSERT INTO MASCOTAS (ID, USUARIO, NOMBRE, EDAD, PESO, SEXO, IMAGEURL, ACTIVO) values (2, 'Diego', 'María', 30, 6, 'Masculino', '/Imagenes/Gato1.jpg', 1);
INSERT INTO MASCOTAS (ID, USUARIO, NOMBRE, EDAD, PESO, SEXO, IMAGEURL, ACTIVO) values (3, 'Diego', 'Pedrito', 25, 5, 'Masculino', '/Imagenes/Perro2.jpg', 1);

CREATE TABLE HIST_MEDICAMENTOS(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(100),
	DOSIS VARCHAR(100),
	DURACION VARCHAR(100),
	FRECUENCIA VARCHAR(100),
	OBS TEXT,
	IDMASCOTA INTEGER,
	FECHA DATE
);


ALTER TABLE HIST_MEDICAMENTOS ADD CONSTRAINT HIST_MEDICAMENTOS_MASCOTAS_FK FOREIGN KEY (IDMASCOTA) REFERENCES MASCOTAS(ID);

INSERT INTO HIST_MEDICAMENTOS (ID, NOMBRE, DOSIS, DURACION , FRECUENCIA, OBS, IDMASCOTA, FECHA) values (1, 'Paracetamol', '500 mg', 'Cada 6 horas', '2 semanas', 'Si no quiere, aplastar el paracetamol', 3, to_date('2025-05-01', 'YYYY-MM-DD'));
INSERT INTO HIST_MEDICAMENTOS (ID, NOMBRE, DOSIS, DURACION , FRECUENCIA, OBS, IDMASCOTA, FECHA) values (2, 'Medicamento SIGCER', '5 gramos', 'Cada 8 horas', '5 dias', 'Con cuidado', 3, to_date('2025-04-12', 'YYYY-MM-DD'));
INSERT INTO HIST_MEDICAMENTOS (ID, NOMBRE, DOSIS, DURACION , FRECUENCIA, OBS, IDMASCOTA, FECHA) values (3, 'Pastilla YUN', '1', '1 vez al dia', '2 meses', 'Aplicar solo una vez por dia', 3, to_date('2025-03-18', 'YYYY-MM-DD'));
INSERT INTO HIST_MEDICAMENTOS (ID, NOMBRE, DOSIS, DURACION , FRECUENCIA, OBS, IDMASCOTA, FECHA) values (4, 'Frenadol', '250 mg', 'Cada 5 horas', '3 semanas', 'No forzar', 3, to_date('2025-02-25', 'YYYY-MM-DD'));


CREATE TABLE HIST_TRATAMIENTOS(
	ID SERIAL PRIMARY KEY,
	TIPO VARCHAR(100),
	DURACION VARCHAR(100),
	FRECUENCIA VARCHAR(100),
	OBS TEXT,
	IDMASCOTA INTEGER,
	FECHA DATE
);

ALTER TABLE HIST_TRATAMIENTOS ADD CONSTRAINT HIST_TRATAMIENTOS_MASCOTAS_FK FOREIGN KEY (IDMASCOTA) REFERENCES MASCOTAS(ID);

INSERT INTO HIST_TRATAMIENTOS (ID, TIPO, DURACION , FRECUENCIA, OBS, IDMASCOTA, FECHA) values (1, 'Masaje', '7 dias', 'Cada 6 horas', 'Con delicadeza', 3, to_date('2025-03-08', 'YYYY-MM-DD'));
INSERT INTO HIST_TRATAMIENTOS (ID, TIPO, DURACION , FRECUENCIA, OBS, IDMASCOTA, FECHA) values (2, 'Estirar patas', '1 semana', '2 veces al dia', 'Mantener en forma a la mascota', 3, to_date('2025-01-30', 'YYYY-MM-DD'));


CREATE TABLE NOTICIAS(
	ID SERIAL PRIMARY KEY,
    TITULO VARCHAR(200),
    DESCRIPCION VARCHAR(500),
    CONTENIDO TEXT,
    AUTOR VARCHAR(500),
    USUARIO VARCHAR(50),
    FECHA TIMESTAMP,
    ImagenURL VARCHAR(500),
	ACTIVO INTEGER DEFAULT 1
);

ALTER TABLE NOTICIAS ADD CONSTRAINT NOTICIAS_USUARIOS_FK FOREIGN KEY (USUARIO) REFERENCES USUARIOS(USUARIO);

CREATE TABLE NOTICIA_PREGUNTAS(
	ID SERIAL PRIMARY KEY,
	IDNOTICIA INTEGER,
	PREGUNTA VARCHAR(250) NOT NULL,
	TEXTOADICIONAL TEXT,
	RESPUESTA_A VARCHAR(100) NOT NULL,
	RESPUESTA_B VARCHAR(100),
	RESPUESTA_C VARCHAR(100),
	RESPUESTA_D VARCHAR(100),
	RESPUESTA VARCHAR(2) NOT NULL
);

ALTER TABLE NOTICIA_PREGUNTAS ADD CONSTRAINT NOTICIA_PREGUNTAS_NOTICIAS_FK FOREIGN KEY (IDNOTICIA) REFERENCES NOTICIAS(ID);

-- ########################################################################################################################################
-- INSERTS
-- ########################################################################################################################################


INSERT INTO PERFILES (CODIGO, DESCRIPCION) VALUES ('GENERICO', 'Perfil Genérico');
INSERT INTO PERFILES (CODIGO, DESCRIPCION) VALUES ('VETERINARIO', 'Perfil Veterinario');
INSERT INTO PERFILES (CODIGO, DESCRIPCION) VALUES ('ADMINISTRADOR', 'Perfil Administrador');

